name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  DOTNET_VERSION: '7.0.x'                 # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Push to Supply Chain Branch
        run: |
          git config --global user.email "github@humana.com"
          git config --global user.name "Github Action"
          git push --force -u origin supply-chain
