name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  DOTNET_VERSION: '7.0.x'                 # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'supply-chain'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
